# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/easterthebunny/spew-order
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /go/src/github.com/easterthebunny/spew-order
    steps:
      - checkout
	  - run: sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
	  - run: wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
	  - run: apt-get update && apt-get -y install gnupg git-secret
	  - run: echo $GPG_PRIVATE_KEY > ./private_key.gpg
	  - run: gpg --import ./private_key.gpg
	  - run: git secret reveal
	  - run: ./configurations/setup
	  - run: ./configurations/deploy-rest
	  - run: ./configurations/deploy-webhooks
	  - run: ./configurations/deploy-audit
	  - run: ./configurations/deploy-book-subscriber
workflows:
  version: 2
  test-release:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - deploy:
          context:
            - PROD
          filters:
            branches:
              only: main
          requires:
            - test
  test-ci:
    jobs:
      - test:
          filters:
            branches:
              only: ci
      - deploy:
          context:
            - CI
          filters:
            branches:
              only: ci
          requires:
            - test
  deploy-uat:
    jobs:
      - test:
          filters:
            branches:
              only: uat
      - deploy:
          context:
            - UAT
          filters:
            branches:
              only: uat
          requires:
            - test