#!/bin/bash

PROJECT=$(echo $PROJECT_ID)
ENVLOC=$(echo "$ENVIRONMENT-$LOCATION")

source ./vars

echo "config gcloud"
gcloud config set project $PROJECT
gcloud config set list project
gcloud auth activate-service-account --key-file=./configurations/key.json

# deploy RestAPI
echo "deploying rest api for $ENVIRONMENT and $LOCATION"
gcloud functions deploy order-api-$ENVLOC \
	--entry-point RestAPI \
	--env-vars-file ./configurations/config.yaml \
	--runtime go113 \
	--trigger-http \
	--allow-unauthenticated