#!/bin/bash

echo "deploying audit api for $ENVIRONMENT and $LOCATION"
ENVLOC=$(echo "$ENVIRONMENT-$LOCATION")

# deploy RestAPI
gcloud functions deploy order-api-$ENVLOC \
	--entry-point AuditAPI \
	--env-vars-file=./configurations/config.yaml \
	--runtime go113 \
	--trigger-http \
	--allow-unauthenticated